### ISSUE TITLE
Chef 14 and 15 support

### ISSUE THREAD

**Issue by martinisoft** [DataDog/chef-handler-datadog#100]
With Chef 10, 11, and 12 officially deprecated as of April of this year, Chef 13 is now the legacy release and Chef 14 is the current release. In less than 6 months, Chef 13 will become EOL while Chef 14 and 15 are the new release. Are there any plans to modernize this handler and reporter?

**Comment by martinisoft** [comment]
I will make note that as of right now, this gem [will not work on Chef 14](https://github.com/DataDog/chef-handler-datadog/blob/34ea86a705ce0c21af175f0641f010137ce96787/chef-handler-datadog.gemspec#L21) which is the current release.

**Comment by olivielpeau** [comment]
@martinisoft: As far as my testing went, the gem should still work with Chef 14. Do you have more info on which parts of the handler need to be modernized?

(I'll update the _development_ version constraint that's defined on the `chef` gem)

The `datadog::dd-handler` recipe (of the [datadog cookbook](https://github.com/DataDog/chef-datadog) which installs this gem, uses the resource provided by the `chef-handler` cookbook instead of the built-in one. I don't think there's a way to make the `datadog` cookbook depend on the `chef-handler` cookbook only if running on Chef 14, unless I'm missing something? So the cookbook will need a major version bump that removes the dependency on `chef-handler` and supports Chef 14+ only

**Comment by martinisoft** [comment]
> (I'll update the development version constraint that's defined on the chef gem)

I've been experimenting with this in my own fork so that would help. Still highly suggest dropping anything before Chef 12 in terms of gem support. The handler interface got much better in Chef 12 and 13 so not nearly as much ceremony needs to happen now.

> The datadog::dd-handler recipe (of the datadog cookbook which installs this gem, uses the resource provided by the chef-handler cookbook instead of the built-in one. I don't think there's a way to make the datadog cookbook depend on the chef-handler cookbook only if running on Chef 14, unless I'm missing something? So the cookbook will need a major version bump that removes the dependency on chef-handler and supports Chef 14+ only

Chef 14 now includes the chef_handler resource so you'll want to make a Chef 13 specific version initially using the chef_handler cookbook resource. You can even use the new gem feature in metadata so you aren't using weird chef_gem tricks to install the gem, it will just auto-install during the compile phase so all you have to do is require it via chef_handler. Once Chef 15 happens in April you can drop the chef_handler cookbook and make it a Chef 14+ cookbook at that point.

**Comment by olivielpeau** [comment]
Thanks, that's very helpful info 👍

> I've been experimenting with this in my own fork so that would help. Still highly suggest dropping anything before Chef 12 in terms of gem support. The handler interface got much better in Chef 12 and 13 so not nearly as much ceremony needs to happen now.

I'm fine with dropping Chef < 12 in the next version of the gem if that simplifies the code.

> Chef 14 now includes the chef_handler resource so you'll want to make a Chef 13 specific version initially using the chef_handler cookbook resource.

I'll have to give this some thought: I might want to extract the `dd-handler` recipe out of the `datadog` cookbook entirely so that we can still support a large number of Chef versions in the next major version of the cookbook, and maintain separately the different versions of `dd-handler` we need for the different versions of Chef we want support.

**Comment by martinisoft** [comment]
> I'll have to give this some thought: I might want to extract the dd-handler recipe out of the datadog cookbook entirely so that we can still support a large number of Chef versions in the next major version of the cookbook, and maintain separately the different versions of dd-handler we need for the different versions of Chef we want support.

I think it can exist even in the form of a resource within the cookbook, but you definitely need to look at letting go of Chef 12 support sooner rather than later. It's EOL as of April and runs with a Ruby that is also EOL and potentially contains vulnerabilities. I'd generally aim at Chef 13 and above. 15 just landed in master in the march towards a stable release in time for April.

**Comment by martinisoft** [comment]
Pinging again on this @olivielpeau as we're approaching our Chef 14 migration point.

**Comment by remeh** [comment]
Released in 0.12.0, thank again!
